steering_engine_hw:
  serial:
    port: "/dev/ttyACM0"
    baudrate: 115200
  imu:
    orientation_covariance_diagonal: [0.0012, 0.0012, 0.0012]
    angular_velocity_covariance_diagonal: [0.0004, 0.0004, 0.0004]
    linear_acceleration_covariance_diagonal: [0.01, 0.01, 0.01]
  protocol:
    id_map:
      left_first_leg_joint: 2
      left_second_leg_joint: 5
      l_gripper_left_drive_joint: 4      
      left_friction_wheel_joint: 3
      right_first_leg_joint: 1
      right_second_leg_joint: 6
      r_gripper_left_drive_joint: 8     
      right_friction_wheel_joint: 7
    control_map:
      wheel_speed_targets:
        - left_friction_wheel_joint
        - right_friction_wheel_joint
      claw_speed_targets:
        - l_gripper_left_drive_joint    
        - r_gripper_left_drive_joint     
      claw_angle_targets:
        - l_gripper_left_drive_joint     
        - r_gripper_left_drive_joint     
      joint_angle_targets:
        - left_first_leg_joint
        - left_second_leg_joint
        - right_first_leg_joint
        - right_second_leg_joint
    topics:
      joint_speed_target: "/joint_speed_target"
      claw_speed_target: "/claw_speed_target"
