b29_controller:
  left_first_leg_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: left_first_leg_joint

  left_second_leg_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: left_second_leg_joint

  right_first_leg_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: right_first_leg_joint

  right_second_leg_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: right_second_leg_joint
